require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

# We use `gems.rb` in this project
Bundler/GemFilename:
  EnforcedStyle: gems.rb

# Totally disable this check
# since we do not use rspec to
# test some code in this product
# but to test another application
RSpec/DescribeClass:
  Enabled: false
