require 'onlyoffice_webdriver_wrapper'

require_relative 'testing_api_onlyoffice_com/config'
require_relative 'testing_api_onlyoffice_com/test_instance'
require_relative 'testing_api_onlyoffice_com/test_manager'
require_relative 'testing_api_onlyoffice_com/test_data'
